### ISSUE TITLE
Potential risk of data loss by encryption

### ISSUE THREAD

**Issue by zhanghanduo** [akhater/Lupin#10]
I tried to encrypt all and it failed in the middle, part of the notes were encrypted and part were not.

Then I `encryptall` again and this time it works, telling me "All your graph contents are now encrypted & I've set AgeEncrypted to true in your config.ini". But I found the contents page has become:
![image](https://user-images.githubusercontent.com/8006682/109505159-46d73b80-7ad7-11eb-9ab9-699ce5fd01ed.png)

Mar 1, 2021 and Feb 28, 2021 also same issue:
![image](https://user-images.githubusercontent.com/8006682/109505420-8a31aa00-7ad7-11eb-9d14-baa594dd7f34.png)

So far haven't found other files corrupted like this.

**Comment by akhater** [comment]
thank u so much for the help ...

**Comment by akhater** [comment]
this should be solved in https://github.com/akhater/Lupin/commit/c6b9239ff1787d6cf109f35669d6643d5dddc33c

**Comment by akhater** [comment]
will close this for now if OK for u
