### ISSUE TITLE
Calendar view option

### ISSUE THREAD

**Issue by zhanghanduo** [akhater/Lupin#11]
We could provide more options to display the calendar.

For me, I would like to display only the current month view, so we could have an option of displaying "current month", "3 consecutive months", etc.  (In the future can even have "week view")

PS: I am sometimes annoyed by clicking on the blank space between dates entering the "edit mode". I know with pure html this cannot be resolved :sweat_smile:

**Comment by akhater** [comment]
Done and up, you can now control how many months (0 to 3) you want LUPIN to generate calendars for, this is controlled thru generateMonths array of config.ini.
first [0|1] specifies if you want LUPIN to generate prev month, second [0|1] specifies if you want LUPIN to generate next month\
1,1 will generate prev,cur,next | 0,1 will generate curr,next | 0,0 will only generate curr'

**Comment by zhanghanduo** [comment]
Love this design!

**Comment by akhater** [comment]
at first run Lupin will "fix" the config.ini and add the generateMonths option, you can after edit it as you please

**Comment by akhater** [comment]
I will close the ticket for now, if  you need it please feel free to re-open it
