### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by justinclarkxyz** [akhater/Lupin#15]
I'm trying to install Lupin for the first time and get the following error:
```
  File "main.py", line 106
    buf.name = f'{PageName}.md'
                              ^
SyntaxError: invalid syntax
```
I'm prepared for the fact that this may be me missing something terribly obvious, but I can't see what it is.

**Comment by akhater** [comment]
Hi Justin,

may I ask which python version are u using?

**Comment by justinclarkxyz** [comment]
I'm on 2.7.16

**Comment by akhater** [comment]
Lupin requires a minimum of version 3.x to run

If you can install version 3.x and give it a try

**Comment by justinclarkxyz** [comment]
Thanks - works as expected with python3.
