### ISSUE TITLE
Hypothe.is tags

### ISSUE THREAD

**Issue by handuozh** [akhater/Lupin#2]
Thanks for the new update for the hypothesis import! 
Just one tiny issue of the tags with multiple words separated by space. Could you transfer the tags into the form of [[]] or #[[]] instead of #?

**Comment by handuozh** [comment]
Another problem is the time zone. As we are in different time zones, the captured timestamp is not the correct time to me.

**Comment by akhater** [comment]
> Another problem is the time zone. As we are in different time zones, the captured timestamp is not the correct time to me.

Lupin will follow the timezone of the server it is running on... if that doesn't work for you please add another issue so I can flag it as feature request 
thanks

**Comment by akhater** [comment]
> Thanks for the new update for the hypothesis import!
> Just one tiny issue of the tags with multiple words separated by space. Could you transfer the tags into the form of [[]] or #[[]] instead of #?

LogSeq doesn't support tags with spaces AFAIK, #[[]] will work as regular pages not tags... do you think it should be converted to tag-with-space ??

**Comment by handuozh** [comment]
> > Another problem is the time zone. As we are in different time zones, the captured timestamp is not the correct time to me.
> 
> Lupin will follow the timezone of the server it is running on... if that doesn't work for you please add another issue so I can flag it as feature request
> thanks

Ahh sorry my mistake. I didn't set the time zone correctly on my VPS. You are right

**Comment by handuozh** [comment]
> > Thanks for the new update for the hypothesis import!
> > Just one tiny issue of the tags with multiple words separated by space. Could you transfer the tags into the form of [[]] or #[[]] instead of #?
> 
> LogSeq doesn't support tags with spaces AFAIK, #[[]] will work as regular pages not tags... do you think it should be converted to tag-with-space ??

I am not sure because in my view tag is equivalent to a page from a technology aspect, although people normally use tags for query and localization.

**Comment by akhater** [comment]
> > > Thanks for the new update for the hypothesis import!
> > > Just one tiny issue of the tags with multiple words separated by space. Could you transfer the tags into the form of [[]] or #[[]] instead of #?
> > 
> > 
> > LogSeq doesn't support tags with spaces AFAIK, #[[]] will work as regular pages not tags... do you think it should be converted to tag-with-space ??
> 
> I am not sure because in my view tag is equivalent to a page from a technology aspect, although people normally use tags for query and localization.

No problem I did both using a config :) you can pick if you want it #[[some tag]] or #some-tag

**Comment by akhater** [comment]
pushed in https://github.com/akhater/Lupin/commit/af1e90d1ed442b3da5096350b2437984efde4523

**Comment by handuozh** [comment]
Nice update. The idea of adding "-" between words seems more reasonable. 🤣
