### ISSUE TITLE
Some websites cannot be imported.

### ISSUE THREAD

**Issue by handuozh** [akhater/Lupin#3]
I don't have enough samples but I met the following error when type `/anno https://moritz.digital/blog/cas`.

```
404
No error handlers are registered logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "main.py", line 58, in hypothesis
    updateJournal(getHypothesisAnnotations(context.args[0]), False, path, True, pageAlias)
  File "/home/xxx/softwares/Lupin.LogSeqPyBot/git.py", line 53, in updateJournal
    data =  "---\ntitle: " + getPageTitle(path) + "\nalias: " + alias + "\n---\n\n" + (entry).strip() + "\n"
TypeError: must be str, not Exception
```

**Comment by akhater** [comment]
Cool thanks for reporting it, I have a pretty good idea what it might be

**Comment by akhater** [comment]
Can you please update and try ?

**Comment by handuozh** [comment]
Thanks! It is fixed~~ 😺. I will try more websites when free.

**Comment by handuozh** [comment]
Hi. I got the following error when entering a url like this: https://twitter.com/arankomatsuzaki/status/1373797309314605059?s=09

```
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "main.py", line 65, in hypothesis
    pageAlias = getWebPageTitle(context.args[0])
  File "/home/christlurker/softwares/Lupin.LogSeqPyBot/utils.py", line 86, in getWebPageTitle
    return soup.title.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by akhater** [comment]
Thank you @handuozh this was fixed (code will be updated soon)
just a question would you be interested in that instead ?
![image](https://user-images.githubusercontent.com/22518020/111980379-e30cc500-8b0e-11eb-8009-4b284b1cde7c.png)

**Comment by handuozh** [comment]
> Thank you @handuozh this was fixed (code will be updated soon)
> just a question would you be interested in that instead ?
> ![image](https://user-images.githubusercontent.com/22518020/111980379-e30cc500-8b0e-11eb-8009-4b284b1cde7c.png)

Yeah! That looks cool! So it seems it's made into an "iframe" right? :sunglasses:

**Comment by akhater** [comment]
yes i did an iframe embed option for Twitter URLs but was about to release it...

👍🏻 or 👎🏻

**Comment by akhater** [comment]
Issue shld be fixed for good in https://github.com/akhater/Lupin/commit/8e43b6503a75bc91e4ecf8febf505bfd110126e8
and also new feature Twitter embed in iframe

Cheers

**Comment by handuozh** [comment]
Thanks and it works!
I wonder is it possible to adjust height of iframe to fit with content in it? Sth like this: https://stackoverflow.com/questions/819416/adjust-width-and-height-of-iframe-to-fit-with-content-in-it

**Comment by akhater** [comment]
i can't use javascript unfortunately .... not supported in LS
