### ISSUE TITLE
task with LATER Command

### ISSUE THREAD

**Issue by santiyounger** [akhater/Lupin#4]
Hey! 

Thanks a lot for the excellent tool

in `config.ini`

there's the following command 

`TODOCommand = TODO`

I have this set to 
`TODOCommand = T` which works great

However I use the Command `LATER` for creating tasks in Logseq

![image](https://user-images.githubusercontent.com/51902730/108529454-7b125700-72a2-11eb-9f3d-b95e9913d7b1.png)

Is is possible to have a quick command for later 

`LATERCommand = LATER`

so that I can set it like this

`LATERCommand = L`

I tried it like that, but doesn't seem to work, I'm sure there's more involved in the code to allow for this to be able to be set. As a non-programmer I looked into the code, but I'm not sure if it's simple or if there's more involved that I'm not aware of.

 if so I'd truly appreciate this feature

Thanks a lot!

**Comment by akhater** [comment]
Something I'd been wanting to do and is on my TODO list, I will get to it,

Thanks for the nudge

**Comment by santiyounger** [comment]
excellent thanks a lot, looking forward to it!

**Comment by akhater** [comment]
added in https://github.com/akhater/Lupin/commit/5f4a3014b89bf6af383e25e60958f60947d41ade

after updating to version https://github.com/akhater/Lupin/releases/tag/v3.3.0e you can add in your config.ini [Misc]
section a CommandsMap = {'T:'TODO', 'L:'LATER', 'D':'DOING'} & map as many commands as you want and Lupin will take care of the rest

**Comment by santiyounger** [comment]
works perfect, I can't believe how fast you got this awesome feature added, thanks a lot!!
