### ISSUE TITLE
Turning off Timestamps

### ISSUE THREAD

**Issue by santiyounger** [akhater/Lupin#5]
I was wondering if it's possible to quickly turn off the timestamps in `config.ini`

In this section
```
[Misc]
hour24 = true
```
If I undesrtand correctly I can set it to `false` to create a 12 hour format, and of course "true" keeps it in a 24 hour format

I'd like to turn it off

I've tried the following things
- commenting it out
- deleting that line
both of these return an error

I've also tried 
```
hour24 = None
hour24 = none
hour24 = null
hour24 = 
```

but I can't seem to get it to hide the time-stamps

This might be a quick solution, but unfortunatly I couldn't figure it out

Thanks!

**Comment by akhater** [comment]
interesting, I never thought someone wld want to turn them off, No worries I will add it just give me a couple of hours

**Comment by akhater** [comment]
Done in https://github.com/akhater/Lupin/commit/b8d0d8a29bf26dba0ed362ca363e23b7a1e116e1

update to https://github.com/akhater/Lupin/releases/tag/v3.2.0e & set timestampEntries = False under [Bot] in the config.ini file to turn it off.

please refer to config.sample.ini for more info

Cheers

**Comment by santiyounger** [comment]
amazing thank you so much! It worked without any issues after updating
