### ISSUE TITLE
Auto generated calendar link to same page

### ISSUE THREAD

**Issue by ethinx** [akhater/Lupin#6]
The auto generated calendar link to the same page (2021-MM-dd) as the snapshot:

![image](https://user-images.githubusercontent.com/965612/108614939-0540f380-743a-11eb-8c84-fef262bb309d.png)

Expect behavior:

Link to the corresponding journal pages

**Comment by akhater** [comment]
Hi,
What is your date-formatter settings please?

**Comment by ethinx** [comment]
> Hi,
> What is your date-formatter settings please?

` :date-formatter "yyyy-MM-dd"`

**Comment by akhater** [comment]
I released a hotfix in https://github.com/akhater/Lupin/commit/bae01b2282a0ca8efa4072e62a217c71fddf676c for that. please update to https://github.com/akhater/Lupin/releases/tag/v3.3.1e and test it.

I'd appreciate if you can report back

**Comment by akhater** [comment]
Issue was auto-closed by Github waiting for your feedback before closing it

@ethinx thank you

**Comment by ethinx** [comment]
Just pull and restart Lupin, it's fixed.

thanks!

**Comment by akhater** [comment]
Closing the issue after your confirmation
