### ISSUE TITLE
Mindmap terminal error

### ISSUE THREAD

**Issue by santiyounger** [akhater/Lupin#7]
Hey there,

I'm excited to test the mind map functionality, I have an error in the terminal that I can't seem to solve.

## What I've done

I have a file called `mindmap1`

which looks like this
![image](https://user-images.githubusercontent.com/51902730/108627795-5db9c600-7425-11eb-9e48-768c902378d4.png)

After making sure Lupin is running correctly, I do the following in Telegram

`/getMM mindmap1`

However the message is stuck in there, without returning the .html file

![image](https://user-images.githubusercontent.com/51902730/108627889-c1dc8a00-7425-11eb-9cf9-8f599bf4b314.png)

Then I checked that there's an error in the terminal

```bash
TypeError: can only concatenate str (not "NoneType") to str
```

## The whole terminal message
```bash
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/santi/.local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/santi/.local/lib/python3.9/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)

  File "/home/santi/Lupin/main.py", line 118, in generateMinmapHTML
    HTMLOut = """
TypeError: can only concatenate str (not "NoneType") to str
```

## Specs

Linux Manjaro
Lupin v3.3.0e
Logseq version 0.0.9
For Lupin I'm using a Github repo in Firefox

Thanks a lot!

**Comment by akhater** [comment]
Hey, would it be possible to attach the MD file ? it is probably some unhandled error from my side

the MD file that generated the error wld help me troubleshoot

thank you

**Comment by akhater** [comment]
I recreated your file but cannot reproduce the issue

![image](https://user-images.githubusercontent.com/22518020/108631504-df841080-7472-11eb-8904-45bc9eb5d4be.png)

![image](https://user-images.githubusercontent.com/22518020/108631511-e90d7880-7472-11eb-9d27-1f99dc4155fd.png)


![image](https://user-images.githubusercontent.com/22518020/108631493-d004c780-7472-11eb-8801-021ae7c296d2.png)

so maybe there is something different in your file... 

so attaching your md file wld really help

**Comment by santiyounger** [comment]
Hey,

Thanks, yeah that's weird not sure what could be causing the issue. My .md file has nothing more to it other than the title I'll add it here just in case.

[mindmap1.tar.gz](https://github.com/akhater/Lupin/files/6018668/mindmap1.tar.gz)

Let me know if there's anything else I can provide to see what could be causing this issue

Thanks a lot

**Comment by akhater** [comment]
Ok that's weird, I tried the md file u sent me & it also worked for me

at this point I can only think that the prob is that u might have run the command before the GitDump.json file is generated

do you have the GitDump.json file ? if so can u please run Lupin and try to run the command again after 1 or 2 min that it starts?

**Comment by akhater** [comment]
I was able to reproduce the error when the Page is not existent so my best guess is that the page isn't in the GitDump.json yet

please try /pullnow first and then /getMM after a min or two

**Comment by santiyounger** [comment]
Hey 

I do have the GitDump.json file. After testing a bit with your suggestions, what worked was running Lupin and waiting 2 minutes. Then after doing `/getMM mindmap1` it generated the file successfully

![image](https://user-images.githubusercontent.com/51902730/108640995-d1ca8d00-746a-11eb-95ea-3726ab1d497d.png)

I wasn't aware of /pullnow what happens when Lupin does a git pull. The way I thought about it was Lupin is constantly pushing to the github repo to add the new added content to Logseq. However I don't fully understand what it's doing when it does a git pull
`GitHubUpdateFrequency = 720`

Would love to know more about why it needs to do pulls, more than anything to have a better understanding of things! other than that thanks for the help the mindmap is looking great!

**Comment by akhater** [comment]
the first version of Lupin used to connect directly to Git as you described, however this was too time consuming for many tasks since there is no really "finding" a file in Git API so you need to list all the files etc...

that's why I moved to dumping everything into a local json file (gitdump.json) which makes the operation much faster

the GitHubUpdateFrequency = 720 is the frequency at which Lupin will update this file in the background. you can force update using /pullnow if needed

**Comment by akhater** [comment]
As a clarification all modifications (push) are done directly to github it is just the "reading" that is cached locally

**Comment by santiyounger** [comment]
Awesome! thanks for the explanation that makes perfect sense, appreciate it!
