### ISSUE TITLE
Encryption exception of image upload

### ISSUE THREAD

**Issue by zhanghanduo** [akhater/Lupin#9]
Hi. I have tested encryption mode for some time.
Normal text works fine only for the first time, but when later I uploaded an image or typed in a simple word, there pops up the following errors:
```
Ignoring unknown recipient type 'BLts-grease'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "main.py", line 87, in image_handler
    updateJournal(path, ignoreURL=True)
  File "/home/christlurker/softwares/Lupin_bot_encrypt/git.py", line 54, in updateJournal
    data =  (AgeEncHandler.ageDecrypt(data))
  File "/home/christlurker/softwares/Lupin_bot_encrypt/AgeEncHandler.py", line 33, in ageDecrypt
    decrypt(infile=io.BytesIO(content),ascii_armored=True)
  File "/home/christlurker/.local/lib/python3.6/site-packages/age/cli.py", line 141, in decrypt
    with Decryptor(keys, infile) as decryptor:
  File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 77, in __init__
    self._decrypt_header(identities)
  File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 108, in _decrypt_header
    HMAC(self._hkdf(HEADER_HKDF_LABEL)).verify(header_stream.getvalue(), mac)
  File "/home/christlurker/.local/lib/python3.6/site-packages/age/primitives/hmac.py", line 48, in verify
    self.mac.verify(tag)
  File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 74, in verify
    ctx.verify(signature)
  File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.
```

Afterward, no matter what I type in, there always have such errors, including `/anno`, etc.

**Comment by zhanghanduo** [comment]
Not only uploading an image, `/anno xxx` also has such an error.

**Comment by zhanghanduo** [comment]
Strangely, after several hours I restart the program and now it works again, with only occasional warning: "Ignoring unknown recipient type '$55-grease' " (but still works). I will keep on watching this issue.

**Comment by zhanghanduo** [comment]
The process "encryptAll" also stuck at some warnings:"Ignoring unknown recipient type ':-grease'
Ignoring unknown recipient type '-gp$#t-grease'"

![image](https://user-images.githubusercontent.com/8006682/109500184-db8a6b00-7ad0-11eb-8367-8d4a368c8543.png)

Then it just hangs there, no further move.

---
Second trial
![image](https://user-images.githubusercontent.com/8006682/109500751-987cc780-7ad1-11eb-8b61-9951843927bf.png)

**Comment by akhater** [comment]
> Hi. I have tested encryption mode for some time.
> Normal text works fine only for the first time, but when later I uploaded an image or typed in a simple word, there pops up the following errors:
> 
> ```
> Ignoring unknown recipient type 'BLts-grease'
> No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
>     handler.handle_update(update, self, check, context)
>   File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
>     return self.callback(update, context)
>   File "main.py", line 87, in image_handler
>     updateJournal(path, ignoreURL=True)
>   File "/home/christlurker/softwares/Lupin_bot_encrypt/git.py", line 54, in updateJournal
>     data =  (AgeEncHandler.ageDecrypt(data))
>   File "/home/christlurker/softwares/Lupin_bot_encrypt/AgeEncHandler.py", line 33, in ageDecrypt
>     decrypt(infile=io.BytesIO(content),ascii_armored=True)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/cli.py", line 141, in decrypt
>     with Decryptor(keys, infile) as decryptor:
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 77, in __init__
>     self._decrypt_header(identities)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 108, in _decrypt_header
>     HMAC(self._hkdf(HEADER_HKDF_LABEL)).verify(header_stream.getvalue(), mac)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/primitives/hmac.py", line 48, in verify
>     self.mac.verify(tag)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 74, in verify
>     ctx.verify(signature)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
>     raise InvalidSignature("Signature did not match digest.")
> cryptography.exceptions.InvalidSignature: Signature did not match digest.
> ```
> 
> Afterward, no matter what I type in, there always have such errors, including `/anno`, etc.

I assume you are uploading the image to the github repo ? in which directory ? /assets?

**Comment by akhater** [comment]
> The process "encryptAll" also stuck at some warnings:"Ignoring unknown recipient type ':-grease'
> Ignoring unknown recipient type '-gp$#t-grease'"
> 
> ![image](https://user-images.githubusercontent.com/8006682/109500184-db8a6b00-7ad0-11eb-8367-8d4a368c8543.png)
> 
> Then it just hangs there, no further move.
> 
> Second trial
> ![image](https://user-images.githubusercontent.com/8006682/109500751-987cc780-7ad1-11eb-8b61-9951843927bf.png)

The warning is normal i am playing around with it now, not able to reproduce the issue /encryptall worked without a blink

are you sure the public / private key are correct in your config.ini ?

**Comment by akhater** [comment]
> Hi. I have tested encryption mode for some time.
> Normal text works fine only for the first time, but when later I uploaded an image or typed in a simple word, there pops up the following errors:
> 
> ```
> Ignoring unknown recipient type 'BLts-grease'
> No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
>     handler.handle_update(update, self, check, context)
>   File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
>     return self.callback(update, context)
>   File "main.py", line 87, in image_handler
>     updateJournal(path, ignoreURL=True)
>   File "/home/christlurker/softwares/Lupin_bot_encrypt/git.py", line 54, in updateJournal
>     data =  (AgeEncHandler.ageDecrypt(data))
>   File "/home/christlurker/softwares/Lupin_bot_encrypt/AgeEncHandler.py", line 33, in ageDecrypt
>     decrypt(infile=io.BytesIO(content),ascii_armored=True)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/cli.py", line 141, in decrypt
>     with Decryptor(keys, infile) as decryptor:
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 77, in __init__
>     self._decrypt_header(identities)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/file.py", line 108, in _decrypt_header
>     HMAC(self._hkdf(HEADER_HKDF_LABEL)).verify(header_stream.getvalue(), mac)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/age/primitives/hmac.py", line 48, in verify
>     self.mac.verify(tag)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 74, in verify
>     ctx.verify(signature)
>   File "/home/christlurker/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
>     raise InvalidSignature("Signature did not match digest.")
> cryptography.exceptions.InvalidSignature: Signature did not match digest.
> ```
> 
> Afterward, no matter what I type in, there always have such errors, including `/anno`, etc.

I can't reproduce this error either 😖

**Comment by akhater** [comment]
please update to https://github.com/akhater/Lupin/commit/c6b9239ff1787d6cf109f35669d6643d5dddc33c and test, I think it should solve most issues here 

thank you

**Comment by handuozh** [comment]
Hi. Never met that strange error output again. But met another typeError, without doing anything.
```
Scheduled Housekeeping ...
Ignoring unknown recipient type '`-grease'
Ignoring unknown recipient type '`-grease'
%b {th}, %Y
%b {th}, %Y
%b {th}, %Y
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "main.py", line 286, in scheduledHousekeeping
    updateCalendarsFile()
  File "/home/christlurker/softwares/Lupin_bot_encrypt/git.py", line 191, in updateCalendarsFile
    contents = AgeEncHandler.ageEncrypt(contents)
  File "/home/christlurker/softwares/Lupin_bot_encrypt/AgeEncHandler.py", line 55, in ageEncrypt
    encrypt(recipients=[config.getAgePublicKey()], infile=io.BytesIO(content), outfile=f,ascii_armored=True)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by akhater** [comment]
That's the price for releasing hasty codes at 3 am :)

**Comment by zhanghanduo** [comment]
Don't push yourself too hard! There is a long road ahead for Lupin and logseq to grow 😺

**Comment by akhater** [comment]
Module should be solid now... I appreciate your help testing

**Comment by zhanghanduo** [comment]
Thanks for the quick fix! It looks good now. 
I will close this for now. (reopen if problem happens again)

BTW, you can remove some warnings like this: "if you are using GitHub as storage, it will only show in the Desktop Application" because logseq now supports assets image display on github.

**Comment by akhater** [comment]
100% :) thanks for the notice
